services:
  golf-shot-server:
      image: pompano-golf-reservation
      restart: unless-stopped
      networks:
        - nginx-proxy
        - sel
      container_name: pompano-golf-reservation
      expose:
        - 8080
      env_file:
        - .env
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

networks:
  nginx-proxy:
    external: true
  sel:
    external: true
